#+PROPERTY: ANKI_DECK Default

*Tip: Click the Raw button on the right to view the original Org file*

* Deck in file
  :PROPERTIES:
  :ANKI_NOTE_TYPE: Cloze
  :END:

** Text

   Cards of this note will be created in {{c1::Default::which deck?}}

* Deck in entry
  :PROPERTIES:
  :ANKI_DECK: Languages
  :ANKI_NOTE_TYPE: Cloze
  :END:

** Text

   Cards of this note will be created in {{c1::Languages::which deck?}}

* Raw fields
  :PROPERTIES:
  :ANKI_NOTE_TYPE: Basic
  :ANKI_FORMAT: nil
  :END:

** Front
   How to send the content of a field or fields to Anki as is?

** Back
   With property <code>:ANKI_FORMAT: nil</code>, content of the
   field will be sent to Anki <em>unprocessed</em>.  You can use
   whatever Anki supports, like HTML tags.
   <br>
   <br>
   This property is retrieved with inheritance, meaning that it can be
   set in any ancestor entries or at the top of the file with
   <code>#+PROPERTY: ANKI_FORMAT nil</code>, it's also possible to
   override an outer level nil format with <code>:ANKI_FORMAT: t</code>.
* Raw and HTML-formatted fields in the same note
  :PROPERTIES:
  :ANKI_NOTE_TYPE: Basic
  :END:

** Front
This field will be formatted as HTML.

** Back
# raw
If you start a field with ~# raw~, the content will be sent to Anki as is.
